### ISSUE TITLE
Disable Sending Data to GA

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#107]
We don't use GA anymore but are still passing data.

I've verified with marketing and they also look at Amplitude now. We also incur expenses for them and they are trying to reduce costs.

Let's at the very least disable it. 

Perhaps we file another bug for completely removing it.

**Comment by shane-tomlinson** [comment]
Thanks @davismtl for checking with everyone and filing this. I migrated this to https://github.com/mozilla/fxa-content-server/issues/6650, the content server is the only source of GA metrics we have.

**Comment by shane-tomlinson** [comment]
Thanks @davismtl for checking with everyone and filing this. I migrated this to https://github.com/mozilla/fxa-content-server/issues/6650, the content server is the only source of GA metrics we have.
