### ISSUE TITLE
Segment the KPI dashboard by browser, operating system and device type

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#11]
Depends on #7.

The KPI dashboard is here:

https://sql.telemetry.mozilla.org/dashboard/fxa-kpis

**Comment by philbooth** [comment]
Related: #20

**Comment by rfk** [comment]
While the queries are still slower than I'd like, I think we can declare success with the following:

  https://sql.telemetry.mozilla.org/queries/1597
  https://sql.telemetry.mozilla.org/queries/1598

Let's include these in the overall dashboard and declare success on the feature as a whole :-)

@philbooth are there other queries that we need to segment?  The DAU/MAU/EGR ones seem like the most important for now.

**Comment by philbooth** [comment]
> ...include these in the overall dashboard...

Done.

Something I tried to do with the other queries was give both the query and the graph distinct titles that make sense from the context of the dashboard. Not sure if you want to do something similar but for DAU and MAU the main title is a little bit misleading and then for engagement ratio the subtitle is a bit repetitive. Just thinking from the point of view of an outsider looking in, or maybe I'm just bike-shedding, ignore me if so.

> ...are there other queries that we need to segment?

I also have some in-progress changes to the time-to-device-connection query that I plan to come back to soon. Leave this open until then?

**Comment by philbooth** [comment]
The time-to-device-connection charts are now segmented by OS but now I've seen it, I don't think it's that useful as a visualization. Happy to remove it if the consensus is that it adds no value.

Either way, this issue is now done.
