### ISSUE TITLE
Make sure we are tracking Screenshot metrics

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#111]
Screenshots is supposed to be rolling out FxA today.

It is unclear to me if we are able to track their logins/installs.

Let's verify that they are passing us the right params AND that we are seeing the event data in Amplitude.

CC @irrationalagent

**Comment by vladikoff** [comment]
Need to talk to Ian abut passing utm params

**Comment by irrationalagent** [comment]
Would they need to add the parameters here: https://github.com/mozilla-services/screenshots/blob/7100bea83ae9f436301c22395e90b4b30b349728/server/src/server.js#L1108 ?

**Comment by shane-tomlinson** [comment]
They aren't passing any UTM params here: https://github.com/mozilla-services/screenshots/blob/7100bea83ae9f436301c22395e90b4b30b349728/server/src/server.js#L1143.

It seems however we should be able to track on their client_id (5e75409a5a3f096d), though when I look for events with that oauth_client_id or service, I come up blank.

**Comment by philbooth** [comment]
@shane-tomlinson: https://analytics.amplitude.com/mozilla-corp/chart/wbs7p7m

**Comment by philbooth** [comment]
(and as per https://analytics.amplitude.com/mozilla-corp/chart/39c1qio, since 8th December you should be able to see them with `service: screenshots` too)

**Comment by shane-tomlinson** [comment]
Thanks for those charts @philbooth. I was looking for `fxa_login - view` and `fxa_reg - view` with that client_id and came up empty.

**Comment by irrationalagent** [comment]
Yea - the service parameter is a good first step but it would still be worth the time for them to pass utm parameters/entrypoint because they get saved as amplitude user properties (rather than event properties, like service) on the view/engage/submit/complete events that allows us to analyze retention etc. by entrypoint/utm_source

**Comment by shane-tomlinson** [comment]
Closing since we have generic data on Screenshots we can use to make decisions.
