### ISSUE TITLE
Make oauth-client-id in Amplitude Readable

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#112]
Currently, it is nearly impossible to make charts by OAuth reliers because most of the client IDs are not readable. They are the actual numbered IDs.

We need to fix this for all the current reliers and avoid this from happening with every new relier.

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by philbooth** [comment]
We might have more success addressing this problem if we provide a list of the specific ids that aren't defined in settings. Blanket-asking for all of them (which I've done, a few times) doesn't seem to be working.

I can go through and collate a list either during or after the All Hands at some point but, in the meantime, if there are some specific ids you can identify right now, I'll call them out in the deployment bug for train 126. (I'll also ask for all of them at the same time, it just might be more effective if we have actual values to call out is all I'm thinking)

**Comment by irrationalagent** [comment]
I'll add some in this comment as I find them:
screenshots = 5e75409a5a3f096d

**Comment by philbooth** [comment]
This was done in https://github.com/mozilla-services/cloudops-deployment/pull/2812, closing.
