### ISSUE TITLE
Remove ${viewName} from begin events, move it to flow_metadata

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#19]
We should probably add a `begin_view` column to the `flow_metadata` table and populate it based on the `viewName` part of `flow.${viewName}.begin`. We could then set the `type` of those begin events to just `flow.begin`, which might make consuming our event data easier for people who lack all the context of content server implementation details. It also makes `flow.begin` nicely symmetrical with `flow.complete`.

Stupidly, when I first thought about this I was envisaging a knock-on change to the content server  and the Heka filter, to set the view name as a field in the event data. But of course there's no need for that, we can just do a separate `UPDATE` after the `INSERT` and pull it out of the `type`, similar to what we do for `duration` etc.

**Comment by rfk** [comment]
We could even consider an explicit event for "saw a view", so the flow would become:
- flow.begin
- flow.${viewName}.view
- flow.${viewName}.engage
- ...
- flow.complete

The timing data on the `flow.${viewName}.view` event would be particularly interesting, as it would more-or-less correspond to the network transit time for our client-side assets.

**Comment by vladikoff** [comment]
cc @philbooth do you want this in active or next 2 weeks?

**Comment by philbooth** [comment]
Yep, next two weeks, 100%, final answer.

**Comment by philbooth** [comment]
This was fixed by #44.
