### ISSUE TITLE
Improve performance of segmented KPI queries

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#20]
I updated the queries for the KPI dashboard to segment users by service and operating system. Quelle surprise, it made everything slower.

The time-to-device-connection query was okay, the execution time only increased to 12 minutes (but also, this query uses flow events, for which we have significantly fewer records). However, the engagement ratio and multi-device user queries became unusable. They were still running when I checked on them after 12 hours and then when I came back to them this morning, they'd failed with an unhelpfully generic error message (which I neglected to copy, sorry). Before I changed them, they were completing in an hour.

Given my poor SQL skills, perhaps there are straightforward improvements that can be made to the queries I produced, which do the job. But I fear the sheer weight of data we have in the activity event tables may call for a more fundamental change.

Incidentally, I also tried to run an `EXPLAIN` on the updated query, but I canceled that when it still hadn't completed after running for 4 hours. Then I tried an `EXPLAIN` on one of the sub-queries, but it complained  that the table needed to be [analyzed](http://docs.aws.amazon.com/redshift/latest/dg/r_ANALYZE.html). So I kicked off an `ANALYZE daily_multi_device_users`, which is still running as I write this, 4 hours later.

In the meantime, I've been doing some reading around the topic of redshift performance and it seems, to my naive understanding, like we have two options if there are no big wins in the query itself:

1. Reduce the amount of data we have. Either by sampling the events that are emitted from the code, or by expiring old data and employing some kind round-robin approach that aggregates it and allows analysis at lower granularity. Neither approach appeals to me at the moment.

2. No idea how reasonable this is in terms of resource usage, but could we have extra copies of the tables that use a different `DISTKEY`? Currently, we use `uid` as `DISTKEY`, what if we created extra tables that used `service` and `ua_os`? Then the segmented queries could target those tables specifically and, presumably, run much faster.

And of course, it's likely there are other things we can do that I don't know about.

@rfk, care to chip in?

**Comment by philbooth** [comment]
For reference, I am pasting the shorter of the two slow queries (engagement ratio), in it's current state. Would be great if somebody could show me how to reduce the number of subqueries and joins I'm using.

``` sql
WITH
   days AS (
    SELECT DISTINCT day
    FROM daily_multi_device_users
    WHERE day - '28 days'::INTERVAL >= (
      SELECT MIN(day)
      FROM daily_multi_device_users
    )
  ),
  dau AS (
    SELECT day, APPROXIMATE COUNT (DISTINCT uid) AS dau
    FROM daily_activity_per_device
    GROUP BY 1
  ),
  mau AS (
    SELECT d.day, APPROXIMATE COUNT(DISTINCT a.uid) AS mau
    FROM days AS d
    INNER JOIN daily_activity_per_device AS a
      ON a.day <= d.day
      AND a.day > d.day - '28 days'::INTERVAL
    GROUP BY 1
  ),
  md_dau AS (
    SELECT day, APPROXIMATE COUNT (DISTINCT uid) AS dau
    FROM daily_multi_device_users
    GROUP BY 1
  ),
  md_mau AS (
    SELECT d.day, APPROXIMATE COUNT(DISTINCT a.uid) AS mau
    FROM days AS d
    INNER JOIN daily_multi_device_users AS a
      ON a.day <= d.day
      AND a.day > d.day - '28 days'::INTERVAL
    GROUP BY 1
  ),
  per_service_dau AS (
    SELECT day, service, APPROXIMATE COUNT (DISTINCT uid) AS dau
    FROM daily_activity_per_device
    GROUP BY 1, 2
  ),
  per_service_mau AS (
    SELECT d.day, a.service, APPROXIMATE COUNT(DISTINCT a.uid) AS mau
    FROM days AS d
    INNER JOIN daily_activity_per_device AS a
      ON a.day <= d.day
      AND a.day > d.day - '28 days'::INTERVAL
    GROUP BY 1, 2
  ),
  per_os_dau AS (
    SELECT day, ua_os, APPROXIMATE COUNT (DISTINCT uid) AS dau
    FROM daily_activity_per_device
    GROUP BY 1, 2
  ),
  per_os_mau AS (
    SELECT d.day, a.ua_os, APPROXIMATE COUNT(DISTINCT a.uid) AS mau
    FROM days AS d
    INNER JOIN daily_activity_per_device AS a
      ON a.day <= d.day
      AND a.day > d.day - '28 days'::INTERVAL
    GROUP BY 1, 2
  )
SELECT
  days.day,
  (1.0 * dau.dau / mau.mau) * 100 AS "engagement ratio",
  (1.0 * md_dau.dau / md_mau.mau) * 100 AS "multi-device engagement ratio",
  (1.0 * sync_dau.dau / sync_mau.mau) * 100 AS "Sync engagement ratio",
  (1.0 * amo_dau.dau / amo_mau.mau) * 100 AS "AMO engagement ratio",
  (1.0 * pocket_dau.dau / pocket_mau.mau) * 100 AS "Pocket engagement ratio",
  (1.0 * testpilot_dau.dau / testpilot_mau.mau) * 100 AS "Test Pilot engagement ratio",
  (1.0 * linux_dau.dau / linux_mau.mau) * 100 AS "Linux engagement ratio",
  (1.0 * mac_dau.dau / mac_mau.mau) * 100 AS "MacOS engagement ratio",
  (1.0 * windows_dau.dau / windows_mau.mau) * 100 AS "Windows engagement ratio",
  (1.0 * android_dau.dau / android_mau.mau) * 100 AS "Android engagement ratio",
  (1.0 * ios_dau.dau / ios_mau.mau) * 100 AS "iOS engagement ratio",
  100 AS "100%",
  0 AS zero
FROM days
INNER JOIN dau
  ON days.day = dau.day
INNER JOIN mau
  ON days.day = mau.day
INNER JOIN md_dau
  ON days.day = md_dau.day
INNER JOIN md_mau
  ON days.day = md_mau.day
INNER JOIN per_service_dau AS sync_dau
  ON days.day = sync_dau.day
  AND sync_dau.service = 'sync'
INNER JOIN per_service_mau AS sync_mau
  ON days.day = sync_mau.day
  AND sync_mau.service = 'sync'
INNER JOIN per_service_dau AS amo_dau
  ON days.day = amo_dau.day
  AND amo_dau.service = 'a4907de5fa9d78fc'
INNER JOIN per_service_mau AS amo_mau
  ON days.day = amo_mau.day
  AND amo_mau.service = 'a4907de5fa9d78fc'
INNER JOIN per_service_dau AS pocket_dau
  ON days.day = pocket_dau.day
  AND pocket_dau.service = '749818d3f2e7857f'
INNER JOIN per_service_mau AS pocket_mau
  ON days.day = pocket_mau.day
  AND pocket_mau.service = '749818d3f2e7857f'
INNER JOIN per_service_dau AS testpilot_dau
  ON days.day = testpilot_dau.day
  AND testpilot_dau.service = '4636d485f6f0c761'
INNER JOIN per_service_mau AS testpilot_mau
  ON days.day = testpilot_mau.day
  AND testpilot_mau.service = '4636d485f6f0c761'
INNER JOIN per_os_dau AS linux_dau
  ON days.day = linux_dau.day
  AND linux_dau.ua_os = 'Linux'
INNER JOIN per_os_mau AS linux_mau
  ON days.day = linux_mau.day
  AND linux_mau.ua_os = 'Linux'
INNER JOIN per_os_dau AS mac_dau
  ON days.day = mac_dau.day
  AND mac_dau.ua_os = 'Macintosh'
INNER JOIN per_os_mau AS mac_mau
  ON days.day = mac_mau.day
  AND mac_mau.ua_os = 'Macintosh'
INNER JOIN per_os_dau AS windows_dau
  ON days.day = windows_dau.day
  AND windows_dau.ua_os LIKE 'Windows%'
INNER JOIN per_os_mau AS windows_mau
  ON days.day = windows_mau.day
  AND windows_mau.ua_os LIKE 'Windows%'
INNER JOIN per_os_dau AS android_dau
  ON days.day = android_dau.day
  AND android_dau.ua_os = 'Android'
INNER JOIN per_os_mau AS android_mau
  ON days.day = android_mau.day
  AND android_mau.ua_os = 'Android'
INNER JOIN per_os_dau AS ios_dau
  ON days.day = ios_dau.day
  AND ios_dau.ua_os LIKE 'iP%' -- iPad, iPhone, iPod
INNER JOIN per_os_mau AS ios_mau
  ON days.day = ios_mau.day
  AND ios_mau.ua_os LIKE 'iP%' -- iPad, iPhone, iPod
ORDER BY 1;
```

**Comment by rfk** [comment]
We could consider making each of the tables in that `WITH` statement a separate derived table, and keeping more history around for those summary tables, while expiring the lower-level event data after e.g. six months.

**Comment by rfk** [comment]
It also looks like the `daily_activity_per_device` table has a large number of unsorted rows:

```
fxa=# SELECT svv_table_info.table, encoded, size, pct_used, empty, unsorted, tbl_rows FROM svv_table_info;

              table               | encoded |  size  | pct_used | empty | unsorted |  tbl_rows  
----------------------------------+---------+--------+----------+-------+----------+------------
...
 activity_events                  | Y       | 552096 |   9.6538 |     0 |     5.32 | 6163672336
...
 flow_events                      | Y       |   3574 |   0.0624 |     0 |     0.00 |   55517988
...
 daily_activity_per_device        | Y       | 311456 |   5.4460 |     0 |    52.45 | 3291632032
 daily_multi_device_users         | Y       |  93148 |   1.6287 |     0 |     8.26 |  791215258
...
```

So we may be able to speed this up a little by  vacuuming it.

In general though I think you're right, we need to work on using more rollups and smaller quantities of raw data.

**Comment by rfk** [comment]
We may also be able to avoid doing so many `INNER JOIN`s in the final query, if we split the segmented one out into a separate graph.  IIRC redash can do a thing where it uses a "group by" column to split up the result into separate groups, as used in e.g. this graph:

  https://sql.telemetry.mozilla.org/queries/866/source#1479

So we could do something similar here, and just select the columns from `per_service_mau` rather than having to make separate columns for `pocket_mau`, `testpilot_mau`, etc.

**Comment by rfk** [comment]
> I also tried to run an EXPLAIN on the updated query, but I canceled that when it still hadn't 
> completed after running for 4 hours

BTW, I find that even "simple" queries like this can be blocked if the DB is running a bunch of analytical queries in the background, e.g. because re:dash has trigger some automatic refreshes.  I sometimes go in to the AWS management console and kill queries that look like they've come from re:dash, in order to free up cycles for interactive queries like this.

**Comment by rfk** [comment]
Here's a snapshot of the query plan I got out of a running query in the AWS management console:

```
----- Update statistics by running the ANALYZE command on these tables -----
----- Tables missing statistics: daily_activity_per_device, daily_multi_device_users -----
----- Nested Loop Join in the query plan - review the join predicates to avoid Cartesian products -----
XN Merge  (cost=1027051894177.04..1027051894178.03 rows=396 width=180)
  ->  XN Network  (cost=1027051894177.04..1027051894178.03 rows=396 width=180)
        ->  XN Sort  (cost=1027051894177.04..1027051894178.03 rows=396 width=180)
              ->  XN Hash Join DS_BCAST_INNER  (cost=26177172610.57..27051894159.95 rows=396 width=180)
                    ->  XN Hash Join DS_BCAST_INNER  (cost=26135903770.95..26970425133.65 rows=394 width=256)
                    ->  XN Hash  (cost=41268839.12..41268839.12 rows=201 width=12)
                          ->  XN Hash Join DS_BCAST_INNER  (cost=26074661013.10..26845182292.27 rows=394 width=232)
                          ->  XN Hash  (cost=61242757.35..61242757.35 rows=200 width=24)
```

There's an expensive "XN Sort" at the top there, and a bunch of "DS_BCAST_INNER" joins.  According to [1]:

  "DS_BCAST_INNER and DS_DIST_BOTH are not good. Usually these redistributions
   occur because the tables are not joined on their distribution keys. "

So this query certainly seems to be doing more work than we think is should.

[1] http://docs.aws.amazon.com/redshift/latest/dg/c_data_redistribution.html

**Comment by rfk** [comment]
@philbooth it's probably worth disabling the re:dash refresh on this query until we've got the performance issues sorted out.  I don't think I can edit it since  you own the query in re:dash.

**Comment by philbooth** [comment]
> ...it's probably worth disabling the re:dash refresh...

Done this now, sorry about that!

**Comment by rfk** [comment]
>  IIRC redash can do a thing where it uses a "group by" column to split up the 
> result into separate groups

FYI I've started experimenting with this for an "Engagement Ratio by OS" graph here:

  https://sql.telemetry.mozilla.org/queries/1597/source#2824

**Comment by philbooth** [comment]
> It also looks like the `daily_activity_per_device` table has a large number of unsorted rows:
> ...
> So we may be able to speed this up a little by  vacuuming it.

I've vacuumed and analysed the tables that are in use. Re-running your `svv_table_info` query now returns the following:

| table | size | pct_used | unsorted | tbl_rows |
| --- | --- | --- | --- | --- |
| `activity_events` | 560,745 | 9.81 | 1.36 | 6,248,712,395.00 |
| `daily_activity_per_device` | 161,782 | 2.83 | 0.39 | 1,703,629,960.00 |
| `daily_multi_device_users` | 95,380 | 1.67 | 0.49 | 808,223,587.00 |
| `flow_events` | 3,574 | 0.06 | 0.00 | 55,517,988.00 |
| `flow_metadata` | 3,130 | 0.05 | 0.00 | 38,380,122.00 |

While doing this, it also occurred to me that it may be time for us to drop all the old tables we still have hanging around? Then we could just run `VACUUM` and `ANALYZE` on the whole database.

I also took a note of how long each query took to run, in case we want to schedule them to run regularly from cron without colliding with other jobs. On each table, `VACUUM` completed in around five seconds. `ANALYZE` was more variable, ranging from a minimum of ~20 seconds for `flow_metadata` to a maximum of ~1 hour for `activity_events`.

**Comment by philbooth** [comment]
> On each table, `VACUUM` completed in around five seconds.

This was both faster and more uniform than I expected. Did you perchance already run a `VACUUM` yourself? Wondering whether mine actually did any work of if they were all nops.

**Comment by philbooth** [comment]
> Did you perchance already run a `VACUUM` yourself?

And if you did, do you know roughly how long it/they took to complete?

**Comment by rfk** [comment]
The above-linked job took a coupe of hours to complete, which is still pretty slow, but an improvement anyways.  Now to try tidying it up a bit...

**Comment by philbooth** [comment]
> The above-linked job took a coupe of hours to complete...

Okay, that's interesting. I made an [equivalent query for services](https://sql.telemetry.mozilla.org/queries/1602/source) and ran it post-`VACUUM`, and it completed in an hour. Hopefully that is a good indicator of how much difference proper sorting can make.

**Comment by rfk** [comment]
>  Did you perchance already run a VACUUM yourself? 

I did run one, but I didn't hang around waiting for it to complete - if it did, it took at least several hours.  But I would expect regular vacuuming jobs to complete more quickly as we keep the size of the unsorted set under control.

**Comment by rfk** [comment]
I wonder if we can do a rollup for the MAU part of this, since this join is often responsible for some serious slowdown:

```
    SELECT d.day, APPROXIMATE COUNT(DISTINCT a.uid) AS mau
    FROM days AS d
    INNER JOIN daily_activity_per_device AS a
      ON a.day <= d.day
      AND a.day > d.day - '28 days'::INTERVAL
    GROUP BY 1
```

Could we maintain a `monthly_activity_per_device` table that's got the 28-day window built in?  It might be a bit yuck to calculate incrementally, but would simplify a lot of these queries.

**Comment by rfk** [comment]
Summary of what I think our biggest bangs-for-buck here will be:
- Regular vacuuming of the tables after import
- Splitting out the segmentations into their own queries, rather than trying to run then all as one big join
- Maintaining a rollup of the 28-day-history query which currently requires a pretty hefty join
- Limiting the query to the last N months, or perhaps trimming the data to the last N months

If a combination of all of those don't give us acceptable performance, we can look at maintaining rollup tables for the actual queries in the `WITH` clause here.

**Comment by philbooth** [comment]
@rfk, can we close this one now?

**Comment by rfk** [comment]
Yeah, let's close this out and revisit with smaller, more focused issues as the need/opportunity arises.  Thanks @philbooth!
