### ISSUE TITLE
Insane flow id field breaking flow event import

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#25]
In the data for the 26th September, there is a weird-looking flow id that fails the import transaction. The full line in the CSV looks like this:

```
1474914688,flow.begin,97cd2d69a3bda79456504302cca75262fd90448e0c42ab2ceedc8f03f53b4f65'"()&%,0,Chrome,41,Windows 7,,,,,,,,,
```

We should add flow id validation to the content server, in the same way we already have for the auth server. We should also tidy up the CSV files so that existing imports can succeed.

**Comment by philbooth** [comment]
There is something very suspicious about that flow id, aside from the invalid trailing characters. If I grep for just the valid part in that day's CSV file, I can see 216 separate `flow.begin` events, all with the same flow id and all with the same timestamp.

Activity of this ilk may be where our rogue future timestamps in https://github.com/mozilla/fxa-activity-metrics/issues/16#issuecomment-257291230 were coming from too I guess. So flow id validation may also be a fix for that problem, although I still think we should pursue the server-side timestamps too.

**Comment by philbooth** [comment]
> There is something very suspicious about that flow id...

And actually, now that I look at the failing line, it does include a fairly lame injection attempt. So validating the flow id as per mozilla/fxa-content-server#4379 is definitely needed.

**Comment by rfk** [comment]
This is almost certainly an automated security scan of some sort, trying a bunch of different injection techniques against our endpoints in the hope that one will produce interesting behaviour.  I agree it would be wise to just drop them on the floor at the ingestion point.

**Comment by philbooth** [comment]
Closing this, we have issues open for validation in the respective repos.
