### ISSUE TITLE
Use 7-day average DAY to smooth the engagement ratio

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-activity-metrics#30]
According to the definitions in [1], engagement ratio is properly calculated as:

"""
"Engagement ratio" on a given day means the mean DAU over the previous 7 days, divided by the MAU for that day, expressed as a percentage.
"""

The seven-day smoothing of DAU eliminates the weekly traffic cycle and makes it easier to see trends in the engagement ratio over time.

I did a quick experiment to see how this would look in re:dash, and it's not *too* bad to calculate this mean at runtime with a join:

   https://sql.telemetry.mozilla.org/queries/1639/source

[1] https://github.com/mozilla/fxa/blob/master/features/FxA-70-kpi-dashboards/README.md#definitions

**Comment by philbooth** [comment]
Done here:

https://sql.telemetry.mozilla.org/queries/1184
