### ISSUE TITLE
Flow event CSVs contain overlapping data

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#33]
On re-running the flow event import just now, I noticed that from the 17th November onwards we receive overlapping timestamps between our daily CSVs:

```
LOADING 81 DAYS OF DATA
LOADING 2016-11-23
  MIN TIMESTAMP 1474316017
  MAX TIMESTAMP 1479968087
LOADING 2016-11-22
  MIN TIMESTAMP 1474616313
  MAX TIMESTAMP 1479879483
LOADING 2016-11-21
  MIN TIMESTAMP 1470904755
  MAX TIMESTAMP 1479821935
LOADING 2016-11-20
  MIN TIMESTAMP 1476423151
  MAX TIMESTAMP 1479697472
LOADING 2016-11-19
  MIN TIMESTAMP 1474316017
  MAX TIMESTAMP 1479626260
LOADING 2016-11-18
  MIN TIMESTAMP 1476519693
  MAX TIMESTAMP 1479526463
LOADING 2016-11-17
  MIN TIMESTAMP 1470239187
  MAX TIMESTAMP 1479491045
LOADING 2016-11-16
  MIN TIMESTAMP 1479254400
  MAX TIMESTAMP 1479340799
```

Currently the import scripts assume that there is no overlap and try to avoid duplicates by first deleting all data for the day that is being imported. It looks like we can't rely on that assumption any more. Presumably this is a side effect of mozilla-services/puppet-config#2368.

I've so far failed to imagine a robust solution to this in the code, but maybe we could add a column to `flow_events` that identifies the originating CSV, then use that column for deletion/avoiding duplicates instead.

**Comment by philbooth** [comment]
If my SQL-fu is right, I think [this query](https://sql.telemetry.mozilla.org/queries/1758/source) shows the duplicate flow events:

```sql
SELECT e.timestamp, e.flow_id, e.type, COUNT(*)
FROM flow_events AS e
GROUP BY 1, 2, 3
HAVING COUNT(*) > 1
ORDER BY 1, 2, 3;
```

There are a few dotted around for our early dates but then they ramp up significantly from the 16th November, as expected.

**Comment by rfk** [comment]
I saw another side-effect of this the other day - if one of the CSV files includes events for the next day, then when we come to import the file for that next day, we look in the db and go "oh, we already have events for that day, must have imported it already" and skip the file.  The effect was we wound up only importing every second day's worth of data.

**Comment by vladikoff** [comment]
@rfk and @philbooth to chat about this..

**Comment by rfk** [comment]
> There are a few dotted around for our early dates but then they ramp up
> significantly from the 16th November, as expected.

To clarify, are these duplicates because we re-imported these files several times, and the import process did not properly delete the older values?

**Comment by philbooth** [comment]
> To clarify, are these duplicates because we re-imported these files several times, and the import process did not properly delete the older values?

Nope. Whenever I've done full re-imports, I've always dropped the tables first just to be on the safe side.

The `expected` part of that comment was just because it is when we see the timestamps begin to overlap between adjacent CSVs. I didn't mean `expected` in some deeper sense where we truly understand the underlying behaviour (although I still assume it's because of that `puppet-config` change).

Regardless, my main objective for fixing this issue is to make the scripts more robust so that it doesn't matter whether there are overlapping timestamps or not, they always produce a 1:1 mapping between CSV and redshift, even after repeated imports.

**Comment by philbooth** [comment]
Fwiw, the log in the first comment shows some extreme overlap that we fixed in train 74, which was deployed on the 24th November. So we should expect to see those fixes take effect from the 25th onwards and indeed we do (I had just enough scroll buffer left in my console to see output from the 25th and 26th):

```
LOADING 2016-11-26
  MIN TIMESTAMP 1480113609
  MAX TIMESTAMP 1480204799
LOADING 2016-11-25
  MIN TIMESTAMP 1480026101
  MAX TIMESTAMP 1480118399
```

The future timestamps have been eliminated from the max values:

```
> new Date(1480118399000)
Fri Nov 25 2016 23:59:59 GMT+0000 (GMT)
> new Date(1480204799000)
Sat Nov 26 2016 23:59:59 GMT+0000 (GMT)
```

And the really old (greater than 2 hours) timestamps have been eliminated from the min values:

```
> new Date(1480026101000)
Thu Nov 24 2016 22:21:41 GMT+0000 (GMT)
> new Date(1480113609000)
Fri Nov 25 2016 22:40:09 GMT+0000 (GMT)
```

With that in mind, I believe this is working as expected now so we can close this. I failed to think about that when I opened this issue, sorry.
