### ISSUE TITLE
Add optional uid field to flow_metadata

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-activity-metrics#36]
I cleared this with the Data Steward in at the all-hands.  Let's add an additional "uid" column to the flow_metadata table, and record the uid involved for flows that get far enough along for us to know it.

In conjunction with https://github.com/mozilla/fxa-content-server/issues/4290, this will help us to a/b test improvements to our signup/signin process.

**Comment by davismtl** [comment]
I had not seen this card. YES!!!

I thought we were not currently allowed. This will make it a lot easier to measure dual device adoption rate per value proposition shown to the users.

**Comment by mhammond** [comment]
> Let's add an additional "uid" column

Can we make it the same "hashed uid" the client records? That might come in handy in the future :)

**Comment by rfk** [comment]
> Can we make it the same "hashed uid" the client records?

Maybe...our metrics pipeline receives these hashed as well but I don't know if the hashing is compatible between the two.  It's probably worthwhile!

**Comment by philbooth** [comment]
I'm going to piggy back on this one to also send the locale in the same changeset (see mozilla/content-server#4694).

**Comment by philbooth** [comment]
Just popping a note in here that it might be easier to do the content server part of this after changes from the private repo have made it back into the public.

This change wants to touch some areas that have diverged significantly. I don't want to perpetuate that divergence for any longer by doing more work in the private repo. And I don't want to make the convergence of the two repos more difficult for whoever does it by introducing new merge conflicts for them to resolve.

**Comment by philbooth** [comment]
Just had a chat with @shane-tomlinson about the conflicting changes, he reckons a couple of weeks is a reasonable ball-park figure for when they'll be merged back to the public repo. That's not a problem, the auth server changes are in, so I can crack on with the data pipeline and the import scripts in the meantime.

Leaving it in active so I don't forget to come back to it then.
