### ISSUE TITLE
Add rollup tables for our core KPI metrics

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-activity-metrics#41]
Re:dash is having a hard time keeping up with our current set of KPI queries, many of which have multi-hour-long runtimes.  It's making it hard to do exploratory analysis, because the redshift query pipeline is almost always full of re:dash queries calculating the same thing over and over again.

Let's try making some rollup tables for the metrics we care about most: DAU, Smoothed DAU and MAU, on an overall, per-service, and per-os basis.  I'm imagining tables like:

* `daily_rollup_engagement` with columns `day`, `dau`, `dau_avg7` and `mau`.
* `daily_rollup_engagement_multi_device` with columns `day`, `dau`, `dau_avg7` and `mau`.
* `daily_rollup_engagement_by_os` with columns `day`, `os`, `dau`, `dau_avg7` and `mau`.
* `daily_rollup_engagement_by_service` with columns `day`, `service`, `dau`, `dau_avg7`, and `mau`.

If that works out OK we can consider rollups for some other metrics as well.  But this should hopefully relieve some of the current pressure from re:dash queries.

**Comment by vladikoff** [comment]
from mtg: down-sampled tables should help with this
