### ISSUE TITLE
Implement automated expiry of old data

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#45]
We've tried a few different tricks to improve query performance but maybe the slowness is a basic facet of the number of events in our tables. This is especially true of activity events, where we have a historical record going back to the start of 2016.

To address this, we could apply a sample rate to the events once they reach an expiry age. This could be handled fairly crudely by a script running, say, every Saturday and deleting *n* of every *nn* events older than a certain date (ordered by timestamp). We could also make this expiry gradual if we're concerned about abrupt boundaries affecting analysis.

For instance:

* age < 3 months, no events deleted; 100% sample rate.
* age >= 3 months && age < 6 months, every other event (when ordered by timestamp) is deleted; 50% sample rate.
* age >= 6 months && age < 2 years, 9 of every 10 events (when ordered by timestamp) are deleted; 10% sample rate.
* age >= 2 years, all events deleted; 0% sample rate.

The reason I suggest ordering by timestamp and then deleting at regular intervals is to preserve the natural daily/seasonal ebb and flow in event frequency. That should hopefully ensure the general shape of our charts remains consistent as expiration progresses.

@rfk, thoughts?

**Comment by philbooth** [comment]
I'm not sure I'd thought this through very clearly when I wrote it down. The most obvious problem with it is that writing queries against a variable sample rate sounds like a complete nightmare. Perhaps a `sample_rate` or `multiplier` column could be added to help with that but it's still pretty awkward.

The other thing that just occurred to me, is the expiration query itself would need to be very careful not to re-sample already-sampled data. The aforementioned extra column would help with that too I guess, but it still feels like it violates the principle of least astonishment somewhat.

**Comment by rfk** [comment]
Some related thoughts in https://github.com/mozilla/fxa-activity-metrics/issues/42

I agree that having different sample-rates of data in the same table is probably asking for trouble.  But I can imagine us maintaining e.g.:

* `activity_events` at 100% sample rate, but only the most recent 3 months of data
* `activity_events_20pct` at 20% sample rate, but only the most recent 6 months of data
* `activity_events_10pct` at 10% sample rate, with a full 2 years of data

That's a little bit of duplication, but probably not very much in the scheme of things, if we choose the sample rates and time intervals properly.

**Comment by philbooth** [comment]
Ah, yeah, separate tables sounds much cleaner, you're right.

And it seems like this is a total dupe of #42, sorry. I'll close this one.
