### ISSUE TITLE
Define and Implement Flow Metrics for SMS feature

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#50]
This card is to make sure that we have defined and then implemented our flow metrics for the SMS feature on email confirmation screen.

Without it, it may prove difficult to measure the success of phase 2, 3 and 4 of this feature.

**Comment by shane-tomlinson** [comment]
We are a ways through this at https://docs.google.com/document/d/133_Cu0TlWQZIw-ihMH1s-U_80I12MXZcvHQEuFhWbPg/edit#heading=h.pxrikbeif9zu

**Comment by shane-tomlinson** [comment]
@philbooth - would you say we've finished this?

**Comment by philbooth** [comment]
I would say so!

**Comment by davismtl** [comment]
Hey, I was just looking over the events. 

Although not related to our flow metrics but related to the metrics to this feature, I added to the Feature document a list of amplitude metrics. (clicks, installs, install rate) We could potentially add retention to that list via Amplitude but I don't think it is part of the success metrics of feature.
