### ISSUE TITLE
Add new tracking parameters for A/B tests and variations

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#56]
There has been a lot of A/B testing going on but no standard for tracking the different cohorts in FxA. The new onboarding team uses entrypoint, I use utm_source and the old onboarding team used utm_campaign.

We need to set a standard.

In the near future though, marketing will pass us UTM parameters to our iFrame. 

This means, we should define new parameters to track test and variations.

These parameters could look something like: ?experiment=name&variation=(A|B|C|D)

How this is stored is up for discussion since it is not unlikely that a user be part of a second A/B test cohort after registration. There is an issue already open for that (add link here)

**Comment by philbooth** [comment]
Taking my face back off this and putting it into next. I think it's slightly different to what we were talking about in the meeting @shane-tomlinson, this is about using query params to force experiments.

**Comment by rfk** [comment]
@philbooth can this now be closed?

**Comment by philbooth** [comment]
@rfk, I don't think so.

Based on the description, I think this issue is for adding query params to the front-end, which can be used to force a user into a specific experiment/cohort.

@davismtl, is that right or have I got the wrong end of the stick?

**Comment by vbudhram** [comment]
from uno: phil says closee
