### ISSUE TITLE
Tweak daily summary tables to enable engagement ratio segmentation

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#7]
The [feature doc](https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards#engagement-ratio) shows the engagement ratio segmented by desktop users, Android users and iOS users. Unless there is some special query magic we can use instead, we'll need to ~~create daily summary tables for these metrics, as we already do for multi-device users~~ add extra columns to the daily summary table for these metrics.

**Comment by philbooth** [comment]
Or, as @rfk pointed out just now, we could create a table of device metadata, similar to `flow_metadata`.

**Comment by rfk** [comment]
> we could create a table of device metadata, similar to flow_metadata.

The difficulty here is that device metadata can change over time, as they e.g. update their browser.  Adding new fields to the `daily_activity_per_device` table seems OK to me on balance.
