### ISSUE TITLE
Increase the amount of memory assigned to work queues?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#74]
In light of #72, I've been going through the common performance problems listed here:

https://aws.amazon.com/blogs/big-data/top-10-performance-tuning-techniques-for-amazon-redshift/

Number 7 from that list, queries that are disk-based, appears to be something we're suffering from. I ran the diagnosis query and there was a heap of results. It can be fixed by increasing the amount of memory available to each queue, but that involves some level of poking about in the AWS console that I'm not entirely comfortable with.

Raising it here so we can discuss whether to address it.

**Comment by vladikoff** [comment]
This is fine now 👍
