### ISSUE TITLE
Add Newsletter Subscription Event to Re:Dash Data

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-activity-metrics#79]
I'd like to be able to measure changes to newsletter subscription by utm_* (used by optimizely tests and funnelcakes).

Are we already measuring that? If so, can we land the data in Redshift? If so, can we backfill?

Thanks

**Comment by philbooth** [comment]
Not sure if this is measured some other way, but we can easily add a flow event for this. Obviously that is no use for backfilling though.
