### ISSUE TITLE
Whittle down the flow events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#80]
This was discussed a few weeks ago but I couldn't find an open issue for it.

The flow events have exploded in number as a natural result of our urge to measure everything. That's fine and completely natural, but now we should be in a position to audit those events and stop emitting any that we're not referencing in queries. Doing this will reduce the amount of data we have in redshift and speed up query performance.

**Comment by vladikoff** [comment]
Closing
