### ISSUE TITLE
How do we develop loops in redshift

### ISSUE THREAD

**Issue by Chiranjeeviv** [mozilla/fxa-activity-metrics#88]
Hi Team,

I have an issue, which requires to run a query for multiple times(for each process_date). Is there any loop facility in redshift to execute the query in one shot?. Appreciate your responses. 

Thanks,
Chiranjeevi Vande

**Comment by philbooth** [comment]
@Chiranjeeviv, sorry I don't know the answer to this.

Maybe you should try asking on StackOverflow? This repo is not really appropriate for general Redshift questions.
