### ISSUE TITLE
Create charts that segment flow completion by performance *times*

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#89]
We have a chart that segments flow completion by performance percentiles:

https://sql.telemetry.mozilla.org/queries/47240#127956

This is really useful, but makes it annoying that you have to look up the concrete values for each percentile in a [separate chart](https://sql.telemetry.mozilla.org/queries/47301#128115).

Instead, we can combine all that data into a single chart by converting the percentiles to concrete upper/lower bounds for stacked bands of timings.

Via @rfk, here's a screenshot of the chart that inspired this issue:

![Screen shot of of a bar chart showing stacked bands of performance timings](https://www.vividcortex.com/hs-fs/hubfs/Screen_Shot_2015-12-07_at_1.00.00_PM.png?t=1502736964815&width=1264&height=488&name=Screen_Shot_2015-12-07_at_1.00.00_PM.png)

**Comment by ckarlof** [comment]
What goes around, comes around. :)

**Comment by philbooth** [comment]
I had a stab at the screenshotted chart here, for completed flows:

https://sql.telemetry.mozilla.org/queries/48363/source#130596

And here, for all flows:

https://sql.telemetry.mozilla.org/queries/48363/source#130597

But actually, the chart I find more interesting than either of those is this one, plotting the % complete flows for each timing band:

https://sql.telemetry.mozilla.org/queries/48363/source#130563

All three are now in the perf dashboard, closing this.

**Comment by ckarlof** [comment]
Those are great, @philbooth, thanks!
