### ISSUE TITLE
Use column compression

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-activity-metrics#9]
We can probably save a lot of disk space by ensuring that we use column compression:

 http://docs.aws.amazon.com/redshift/latest/dg/t_Compressing_data_on_disk.html

Unfortunately it might require dropping and re-creating our tables, but it will be interesting to do some analysis and see if the gain is worth it.  At the very least, we should decide what compression would be useful for when we re-create these tables under Ops control.

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this?

**Comment by rfk** [comment]
Redshift has a thing that will suggest compression schemes based on existing table data, here's what it says for ours:

```
analyze compression activity_events
fxa-# ;
      Table      |   Column   | Encoding 
-----------------+------------+----------
 activity_events | timestamp  | lzo
 activity_events | uid        | lzo
 activity_events | type       | lzo
 activity_events | device_id  | lzo
 activity_events | service    | lzo
 activity_events | ua_browser | lzo
 activity_events | ua_version | lzo
 activity_events | ua_os      | bytedict
(8 rows)
```

TBH I'm surprised it didn't recommend delta-compression for the timestamp columns, but _shrug_

**Comment by rfk** [comment]
I copied our existing activity-events table into a compressed version, and it made a pretty big difference:

```
 fxa=# SELECT svv_table_info.table, encoded, size, pct_used, empty, unsorted, tbl_rows FROM svv_table_info;

             table               | encoded |  size  | pct_used | empty | unsorted |  tbl_rows  
---------------------------------+---------+--------+----------+-------+----------+------------
compressed_activity_events       | Y       | 518694 |   9.0697 |     0 |     0.00 | 5835574900
activity_events                  | N       | 885298 |  15.4801 |     0 |     3.38 | 5835574900
```

It also seems to have dramatically improved performance of scanning the table:
- `select min(timestamp) from compressed_activity_events` -> about 40 seconds
- `select min(timestamp) from activity_events` -> several minutes

So I'm going to go ahead and compress the existing tables, and have made a PR to record the change for future use: https://github.com/mozilla/fxa-activity-metrics/issues/13

**Comment by rfk** [comment]
I've updated activity-event and flow-event tables to use compression.  Since we're planning on changing the schema for the rollup tables anyway, we can convert them to use compression as part of that work.

**Comment by rfk** [comment]
We're now doing this on all tables, closing
