### ISSUE TITLE
Set up a private WebPageTest instance inside the dev IAM

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#93]
This is definitely the wrong place for this issue but never mind.

We should spin up a WebPageTest instance inside the dev IAM and configure automated runs against `master` and pull requests, so that we can detect and prevent performance regressions before they reach production.

Median results from the `master` runs should be exported to redshift on a daily basis, so that we can track them on the [perf dashboard](https://sql.telemetry.mozilla.org/dashboard/fxa-performance).

**Comment by philbooth** [comment]
Splendid news arrives via the IRC grapevine:

```
10:23:06 <stephend> what I'm doing now for the AMO team is super, super basic: https://github.com/stephendonner/webpagetest-amo running in Jenkins, against an internal WPT-API AMI, provisioned by Cloud Ops
10:23:29 <stephend> using https://github.com/marcelduran/webpagetest-api to drive it
10:24:05 <stephend> pb: not sure if you looked at or are interested in https://github.com/wikimedia/wpt-reporter
```

So there is already an internal WebPageTest AMI, provisioned by cloud-ops. Re-using that will make starting this work a great deal easier.

**Comment by philbooth** [comment]
I've reduced the scope of this issue to make it more plausibly fit inside a single sprint; it is purely for setting up the private WPT instance now. The other work is covered by the following issues:

* #98
* mozilla/fxa-content-server#5845
* mozilla/fxa-content-server#5846

**Comment by philbooth** [comment]
Bug for provisioning opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1437936

**Comment by davismtl** [comment]
@philbooth any update? Do we move this to 116?

**Comment by philbooth** [comment]
This and the other issues from this milestone are clearly not happening. It is time to accept I failed.
